---
- block:
  - name: "Read Job Templates definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_job_templates.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Job Templates list"
    set_fact:
      populate_controller_job_templates: "{{ (populate_controller_job_templates | default([])) + item.ansible_facts.controller_templates }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_templates is defined

  - name: "Set Job Templates Data Structure"
    set_fact:
      controller_templates: "{{ populate_controller_job_templates }}"
    when: populate_controller_job_templates is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Job Templates | Launch job_templates creation
  import_role:
    name: redhat_cop.controller_configuration.job_templates
...
