---
# tasks file for casc_desired_state
#
# - name: Include Tasks to configure Controller Roles
#   include_tasks: roles_desired_state.yml
#   args:
#     apply:
#       tags: desired_state_roles
#   tags:
#     - desired_state
#     - desired_state_roles

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE  Schedules

- block:
    - name: "Get the Authentication Token for the future requests"
      uri:
        url: "https://{{ controller_hostname }}/api/v2/tokens/"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: POST
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 201
      register: authtoken_res

    - name: "Set the oauth token to be used since now"
      set_fact:
        oauthtoken: "{{ authtoken_res.json.token }}"
        oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: true

  tags:
    - desired_state
    - desired_state_workflow_job_templates
    - desired_state_job_templates
    - desired_state_teams
    - desired_state_user_accounts
    - desired_state_groups
    - desired_state_hosts
    - desired_state_inventory_sources
    - desired_state_inventories
    - desired_state_projects
    - desired_state_credentials
    - desired_state_organizations

- name: Include Tasks to configure Controller Workflow Job Templates
  include_tasks: workflow_job_templates_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_workflow_job_templates
  tags:
    - desired_state
    - desired_state_workflow_job_templates

- name: Include Tasks to configure Controller Job Templates
  include_tasks: job_templates_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_job_templates
  tags:
    - desired_state
    - desired_state_job_templates

# REVIEW - TODO - Not delete FROM External Source - LDAP
# desired_state_teams It must be defined to run the Team's desired state.
# https://issues.redhat.com/projects/AAP/issues/AAP-2393
- name: Include Tasks to configure Controller Teams
  include_tasks: teams_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_teams
  tags:
    - desired_state
    - desired_state_teams
  when: desired_state_teams is defined

- name: Include Tasks to config DESIRED STATE User Accounts
  include_tasks: user_accounts_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_user_accounts
  tags:
    - desired_state
    - desired_state_user_accounts

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE Instance Groups

- name: Include Tasks to config DESIRED STATE groups
  include_tasks: groups_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_groups
  tags:
    - desired_state
    - desired_state_groups

- name: Include Tasks to config DESIRED STATE hosts
  include_tasks: hosts_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_hosts
  tags:
    - desired_state
    - desired_state_hosts

- name: Include Tasks to configure Controller Inventory Sources
  include_tasks: inventory_sources_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_inventory_sources
  tags:
    - desired_state
    - desired_state_inventory_sources

- name: Include Tasks to configure Controller Inventories
  include_tasks: inventories_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_inventories
  tags:
    - desired_state
    - desired_state_inventories

- name: Include Tasks to config DESIRED STATE Projects
  include_tasks: projects_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_projects
  tags:
    - desired_state
    - desired_state_projects

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE credential_input_sources

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE credential_types
#   include_tasks: credential_types_desired_state.yml
#   args:
#     apply:
#       tags:
#        - desired_state
#        - desired_state_credential_types
#   tags:
#     - desired_state
#     - desired_state_credential_types

- name: Include Tasks to config DESIRED STATE credentials
  include_tasks: credentials_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_credentials
  tags:
    - desired_state
    - desired_state_credentials

# REVIEW - TODO
# - name: Include Tasks to configure Controller Excecution Environments
#   include_tasks: excecution_environments_desired_state.yml
#   args:
#     apply:
#       tags:
#         - desired_state
#         - desired_state_excecution_environments
#   tags:
#     - desired_state
#     - desired_state_excecution_environments

- name: Include Tasks to config DESIRED STATE Organizations
  include_tasks: organizations_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_organizations
  tags:
    - desired_state
    - desired_state_organizations

# - name: Include Tasks to configure Controller Schedules
#   include_tasks: schedules_desired_state.yml
#   args:
#     apply:
#       tags:
#         - desired_state
#         - desired_state_schedules
#   tags:
#     - desired_state
#     - desired_state_schedules

...
