---
# defaults file for casc_implementation

# Organization and Environment Variables
orgs: "Acme"
dir_orgs_vars: orgs_vars
env: dev

# Authentication
controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
controller_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"

# Controller lists

controller_settings: []
controller_organizations: []
controller_labels: []
controller_user_accounts: []
controller_teams: []
controller_credential_types: []
controller_credentials: []
controller_credential_input_sources: []
controller_notifications: []
controller_projects: []
controller_execution_environments: []
controller_applications: []
controller_inventories: []
controller_inventory_sources: []
controller_instance_groups: []
controller_hosts: []
controller_groups: []
controller_templates: []
controller_workflow_job_templates: []
controller_schedules: []
controller_roles: []

# Controller Directory Path
filetree_controller_settings: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_settings.d/"
filetree_controller_organizations: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_organizations.d/"
filetree_controller_labels: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_labels.d/"
filetree_controller_user_accounts: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_users.d/"
filetree_controller_teams: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_teams.d/"
filetree_controller_credential_types: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_types.d/"
filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"
filetree_controller_credential_input_sources: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_input_sources.d/"
filetree_controller_notifications: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_notification_templates.d/"
filetree_controller_projects: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_projects.d/"
filetree_controller_execution_environments: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_execution_environments.d/"
filetree_controller_applications: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_applications.d/"
filetree_controller_inventories: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_inventories.d/"
filetree_controller_inventory_sources: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_inventory_sources.d/"
filetree_controller_instance_groups: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_instance_groups.d/"
filetree_controller_hosts: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_hosts.d/"
filetree_controller_groups: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_groups.d/"
filetree_controller_templates: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_job_templates.d/"
filetree_controller_workflow_job_templates: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_workflow_job_templates.d/"
filetree_controller_schedules: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_schedules.d/"
filetree_controller_roles: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_roles.d/"
...
