---
# tasks file for controller_credentials
- block:
  - name: "Read Credentials definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Credentials list"
    set_fact:
      populate_controller_credentials: "{{ (populate_controller_credentials | default([])) + item.ansible_facts.controller_credentials }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_credentials is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_credentials: "{{ populate_controller_credentials }}"
    when: populate_controller_credentials is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- block:

    - name: Get the organization ID
      set_fact:
        __controller_organization_id: "{{ lookup('ansible.controller.controller_api', 'organizations', query_params={ 'name': orgs },
          host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

    - name: "DESIRED STATE: Get the API list of all Projects {{ orgs }} Organization"
      set_fact:
        __controller_api_credentials: "{{ query('ansible.controller.controller_api', 'credentials',
          query_params={ 'organization': __controller_organization_id.id },
          host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

    - name: "DESIRED STATE: Find the difference of Project between what is on the Controller versus CasC on SCM"
      set_fact:
        __credentials_difference: "{{ lookup('redhat_cop.controller_casc.controller_object_diff_temp',
          api_list=__controller_api_credentials, compare_list=controller_credentials,
          with_present=false, set_absent=true ) }}"

    - name: "DESIRED STATE: Set credential's list to be configured"
      set_fact:
        controller_credentials: "{{ __credentials_difference }}"

- name: "DESIRED STATE: Configure Controller Credetials"
  import_role:
    name: redhat_cop.controller_configuration.credentials
...
