---
- block:
  - name: "Read Job Templates definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_job_templates.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Job Templates list"
    set_fact:
      populate_controller_job_templates: "{{ (populate_controller_job_templates | default([])) + item.ansible_facts.controller_templates }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_templates is defined

  - name: "Set Job Templates Data Structure"
    set_fact:
      controller_templates: "{{ populate_controller_job_templates }}"
    when: populate_controller_job_templates is defined

  when: orgs is defined and dir_orgs_vars is defined

- block:

    - name: Get the organization ID
      set_fact:
        __controller_organization_id: "{{ lookup('ansible.controller.controller_api', 'organizations', query_params={ 'name': orgs },
          host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

    - name: "DESIRED STATE: Get the API list of all Job Templates {{ orgs }} Organization"
      set_fact:
        __controller_api_job_templates: "{{ query('ansible.controller.controller_api', 'job_templates',
          query_params={ 'organization': __controller_organization_id.id },
          host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

    - name: "DESIRED STATE: Find the difference of Job Templates between what is on the Controller versus CasC on SCM"
      set_fact:
        __job_templates_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
          api_list=__controller_api_job_templates, compare_list=controller_templates,
          with_present=false, set_absent=true ) }}"

    - name: "DESIRED STATE: Set job_template's list to be configured"
      set_fact:
        controller_templates: "{{ __job_templates_difference }}"

    - name: "DESIRED STATE: Configure Controller Job Templates"
      import_role:
        name: redhat_cop.controller_configuration.job_templates
...
