# tasks file for controller_casc_desired_state
#
#- name: Include Tasks to configure Controller Roles
#  include_tasks: roles_desired_state.yml
#  args:
#    apply:
#      tags: desired_state_roles
#  tags:
#    - desired_state
#    - desired_state_roles

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE  Schedules

- name: Include Tasks to configure Controller Workflow Job Template Nodes
  include_tasks: workflow_job_template_nodes_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_workflow_job_template_nodes
  tags:
    - desired_state
    - desired_state_workflow_job_template_nodes

- name: Include Tasks to configure Controller Workflow Job Templates
  include_tasks: workflow_job_templates_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_workflow_job_templates
  tags:
    - desired_state
    - desired_state_workflow_job_templates

- name: Include Tasks to configure Controller Job Templates
  include_tasks: job_templates_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_job_templates
  tags:
    - desired_state
    - desired_state_job_templates

# REVIEW - TODO - Not delete FROM External Source - LDAP
- name: Include Tasks to configure Controller Teams
  include_tasks: teams_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_teams
  tags:
    - desired_state
    - desired_state_teams

# REVIEW - TODO - Not delete FROM External Source - LDAP
- name: Include Tasks to config DESIRED STATE User Accounts
  include_tasks: user_accounts_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_user_accounts
  tags:
    - desired_state
    - desired_state_user_accounts

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE Instance Groups

- name: Include Tasks to config DESIRED STATE groups
  include_tasks: groups_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_groups
  tags:
    - desired_state
    - desired_state_groups

- name: Include Tasks to config DESIRED STATE hosts
  include_tasks: hosts_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_hosts
  tags:
    - desired_state
    - desired_state_hosts

- name: Include Tasks to configure Controller Inventory Sources
  include_tasks: inventory_sources_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_inventory_sources
  tags:
    - desired_state
    - desired_state_inventory_sources

- name: Include Tasks to configure Controller Inventories
  include_tasks: inventories_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_inventories
  tags:
    - desired_state
    - desired_state_inventories

- name: Include Tasks to config DESIRED STATE Projects
  include_tasks: projects_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_projects
  tags:
    - desired_state
    - desired_state_projects

# REVIEW - TODO
# - name: Include Tasks to config DESIRED STATE credential_input_sources

# REVIEW - TODO
#- name: Include Tasks to config DESIRED STATE credential_types
#  include_tasks: credential_types_desired_state.yml
#  args:
#    apply:
#      tags:
#       - desired_state
#       - desired_state_credential_types
#  tags:
#    - desired_state
#    - desired_state_credential_types

- name: Include Tasks to config DESIRED STATE credentials
  include_tasks: credentials_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_credentials
  tags:
    - desired_state
    - desired_state_credentials

# REVIEW - TODO
#- name: Include Tasks to configure Controller Excecution Environments
#  include_tasks: excecution_environments_desired_state.yml
#  args:
#    apply:
#      tags:
#        - desired_state
#        - desired_state_excecution_environments
#  tags:
#    - desired_state
#    - desired_state_excecution_environments

- name: Include Tasks to config DESIRED STATE Organizations
  include_tasks: organizations_desired_state.yml
  args:
    apply:
      tags:
        - desired_state
        - desired_state_organizations
  tags:
    - desired_state
    - desired_state_organizations

#- name: Include Tasks to configure Controller Schedules
#  include_tasks: schedules_desired_state.yml
#  args:
#    apply:
#      tags:
#        - desired_state
#        - desired_state_schedules
#  tags:
#    - desired_state
#    - desired_state_schedules

...
