---
- block:
  - name: "Read Organization definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_organizations.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Organizations list"
    set_fact:
      populate_controller_organizations: "{{ (populate_controller_organizations | default([])) + item.ansible_facts.controller_organizations }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_organizations is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_organizations: "{{ populate_controller_organizations }}"
    when: populate_controller_organizations is defined

  when: orgs is defined and dir_orgs_vars is defined

- name: "Gets current Organizations configured"
  set_fact:
    __controller_api_organizations: "{{ query('ansible.controller.controller_api', 'organizations',
      host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=controller_validate_certs) }}"

- name: "DESIRED STATE: Find the difference of Organizations between what is on the Controller versus curated list."
  set_fact:
    __organizations_difference: "{{ lookup('redhat_cop.controller_casc.controller_object_diff_temp',
      api_list=__controller_api_organizations, compare_list=controller_organizations,
      with_present=false, set_absent=true ) }}"

- name: "Sets Organization differences"
  set_fact:
    controller_organizations: "{{ __organizations_difference }}"

- name: "DESIRED STATE: Configure Controller Projects | Launch project creation"
  import_role:
    name: redhat_cop.controller_configuration.organizations
...
