---
- name: "DESIRED STATE: configure_controller_organizations"
  include_vars:
    file: "{{ item }}"
  loop:
    - "{{ dir_orgs_vars }}/env/common/configure_controller_organizations.yml"
  when: dir_orgs_vars is defined

- set_fact:
       __controller_api_organizations: "{{ lookup('ansible.controller.controller_api', 'organizations',
         host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

- name: "DESIRED STATE: Find the difference of Organizations between what is on the Controller versus curated list."
  set_fact:
    __organizations_difference: "{{ lookup('redhat_cop.controller_casc.controller_object_diff_temp',
      api_list=__controller_api_organizations, compare_list=controller_organizations,
      with_present=true, set_absent=true ) }}"

- debug:
    var: "{{ item }}"
  loop:
      - __organizations_difference

- set_fact:
    controller_organizations: "{{ __organizations_difference }}"

- name: Configure Controller Projects | Launch project creation
  import_role:
    name: redhat_cop.controller_configuration.organizations
...
