---
- block:
  - name: "Read Teams definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_teams.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Teams list"
    set_fact:
      populate_controller_teams: "{{ (populate_controller_teams | default([])) + item.ansible_facts.controller_teams }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_teams is defined

  - name: "Set Teams Data Structure"
    set_fact:
      controller_teams: "{{ populate_controller_teams }}"
    when: populate_controller_teams is defined

  when: orgs is defined and dir_orgs_vars is defined

- name: "DESIRED STATE: Get the current controller user to determine if it is super-admin"
  set_fact:
       __controller_api_current_user_check_is_admin: "{{ lookup('ansible.controller.controller_api', 'users', query_params={ 'username': controller_username },
         host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"
- block:
    - name: Get the organization ID
      set_fact:
        __controller_organization_id: "{{ lookup('ansible.controller.controller_api', 'organizations', query_params={ 'name': orgs },
          host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

    - name: "DESIRED STATE: Get the API list of all teams {{ orgs }} Organization"
      set_fact:
        __controller_api_teams: "{{ query('ansible.controller.controller_api', 'teams',
          query_params={ 'organization': __controller_organization_id.id },
          host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

    - name: "DESIRED STATE: Find the difference of Teams between what is on the Controller versus CasC on SCM"
      set_fact:
        __teams_difference: "{{ lookup('redhat_cop.controller_casc.controller_object_diff_temp',
          api_list=__controller_api_teams, compare_list=controller_teams,
          with_present=false, set_absent=true ) }}"

    - name: "DESIRED STATE: Sets the difference of Teams between what is on the Controller versus CasC on SCM"
      set_fact:
        controller_teams: "{{ __teams_difference }}"

    - name: "DESIRED STATE: Configure Controller Teams"
      import_role:
        name: redhat_cop.controller_configuration.teams

  when:
    - __controller_api_current_user_check_is_admin.is_superuser
...
