---
- block:
  - name: "Read Galaxy Credentials definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/env/{{ env }}/controller_galaxy_credentials.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Galaxy Credentials list"
    set_fact:
      populate_controller_galaxy_credentials: "{{ (populate_controller_galaxy_credentials | default([])) + item.ansible_facts.controller_credentials }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_credentials is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_credentials: "{{ populate_controller_galaxy_credentials }}"
    when: populate_controller_credentials is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- name: Configure Controller Galaxy Credentials | Launch galaxy credential creation
  import_role:
    name: redhat_cop.controller_configuration.credentials
...
