---
- block:
  - name: "Read Instance Groups definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_instance_groups.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Instance Groups list"
    set_fact:
      populate_controller_instance_groups: "{{ (populate_controller_instance_groups | default([])) + item.ansible_facts.controller_instance_groups }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_instance_groups is defined

  - name: "Set Instance Groups Data Structure"
    set_fact:
      controller_instance_groups: "{{ populate_controller_instance_groups }}"
    when: populate_controller_instance_groups is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Instance Groups | Launch instance_groups creation
  import_role:
    name: redhat_cop.controller_configuration.instance_groups
...
