---
- name: "Create the output directory: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory

- debug:
    msg: "{{ current_asset_value }}"

- name: "Add current credentials to the output yaml file: {{ output_path }}/current_credentials.yaml"
  template:
    src: "templates/current_credentials.j2"
    dest: "{{ output_path }}/current_credentials.yaml"
...
