---
- name: "Create the output directory: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory

- name: "Add current hosts to the output yaml file: {{ output_path }}/current_hosts_{{ current_asset_value.key }}.yaml"
  template:
    src: "templates/current_hosts.j2"
    dest: "{{ output_path }}/current_hosts_{{ current_asset_value.key }}.yaml"
...
