---
- name: "Get current Job Templates from the API"
  set_fact:
    jt_lookvar: "{{ query('ansible.controller.controller_api', 'api/v2/job_templates/', host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs, return_all=true) }}"

- name: "Create the output directory: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current job templates to the output yaml file: {{ output_path }}/current_job_templates.yaml"
  template:
    src: "templates/current_job_templates_improved.j2"
    dest: "{{ output_path }}/current_job_templates.yaml"
    mode: '0644'
  vars:
    current_job_templates_asset_value: "{{ jt_lookvar }}"
...
