---
- block:
  - name: "Read Organization definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/env/common/controller_organizations.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Organizations list"
    set_fact:
      populate_controller_organizations: "{{ (populate_controller_organizations | default([])) + item.ansible_facts.controller_organizations }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_organizations: "{{ populate_controller_organizations }}"
    when: populate_controller_organizations is defined

  when: orgs is defined and dir_orgs_vars is defined

- name: "Configure Controller Organizations"
  import_role:
    name: redhat_cop.controller_configuration.organizations
...
