---
- block:
  - name: "Read Teams definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_teams.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Teams list"
    set_fact:
      populate_controller_teams: "{{ (populate_controller_teams | default([])) + item.ansible_facts.controller_teams }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Teams Data Structure"
    set_fact:
      controller_teams: "{{ populate_controller_teams }}"
    when: populate_controller_teams is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Teams | Launch teams creation
  import_role:
    name: redhat_cop.controller_configuration.teams
...
