---
- set_fact:
    lookvar: "{{ query('ansible.controller.controller_api', 'api/v2/workflow_job_template_nodes/', host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=controller_validate_certs, return_all=true) }}"

- name: "Create the output directory: {{ output_path }}"
  file:
    path: "{{ output_path }}"
    state: directory

- name: "Add current workflow job template nodes to the output yaml file: {{ output_path }}/current_workflow_job_template_nodes_{{ worflow_job_template_name }}.yaml"
  template:
    src: "templates/current_workflow_job_template_nodes_improved.j2"
    dest: "{{ output_path }}/current_workflow_job_template_nodes_{{ worflow_job_template_name }}.yaml"
  vars:
    worflow_job_template_name: "{{ query('ansible.controller.controller_api', lookvar[0].related.workflow_job_template, host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=controller_validate_certs)[0].name }}"
    worflow_job_template_organization: "{{ query('ansible.controller.controller_api', lookvar[0].related.workflow_job_template, host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=controller_validate_certs)[0].summary_fields.organization.name }}"
    current_asset_value: "{{ lookvar }}"
...
