---
- block:
  - name: "Read Inventory Source definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_inventory_sources.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Inventory Source list"
    set_fact:
      __populate_controller_inventory_source_update: "{{ (populate_controller_inventory_source_update | default([])) + item.ansible_facts.controller_inventory_sources }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_inventory_sources is defined

  - name: "Set Inventory Source Data Structure"
    set_fact:
      controller_inventory_sources: "{{ __populate_controller_inventory_source_update }}"
    when: __populate_controller_inventory_sources is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined


- name: Update Controller Inventory Sources | Launch inventory Source Update
  import_role:
    name: redhat_cop.controller_configuration.inventory_source_update
...
