---
- block:
  - name: "Read Credential Input Sources definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_input_sources.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Credential Input Sources list"
    set_fact:
      populate_controller_credential_input_sources: "{{ (populate_controller_credential_input_sources | default([])) + item.ansible_facts.controller_credential_input_sources }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Credential Input Sources Data Structure"
    set_fact:
      controller_credential_input_sources: "{{ populate_controller_credential_input_sources }}"
    when: populate_controller_credential_input_sources is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Credential Input Sources | Launch credential_input_sources creation
  import_role:
    name: redhat_cop.controller_configuration.credential_input_sources
...
