---
- block:
  - name: "Read Credential_Types definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_types.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Credential_Types list"
    set_fact:
      populate_controller_credential_types: "{{ (populate_controller_credential_types | default([])) + item.ansible_facts.controller_credential_types }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_credential_types: "{{ populate_controller_credential_types }}"
    when: populate_controller_credential_types is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- name: Configure Controller Credential_Types | Launch credential creation
  import_role:
    name: redhat_cop.controller_configuration.credential_types
...
