---
- block:
  - name: "Read Credentials definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Credentials list"
    set_fact:
      populate_controller_credentials: "{{ (populate_controller_credentials | default([])) + item.ansible_facts.controller_credentials }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_credentials: "{{ populate_controller_credentials }}"
    when: populate_controller_credentials is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- name: Configure Controller Credentials | Launch credential creation
  import_role:
    name: redhat_cop.controller_configuration.credentials

- name: Include Tasks to config galaxy credentials to Organizations
  include_tasks: organizations.yml
  vars:
    assign_galaxy_credentials_to_org: true
...
