---
- block:
  - name: "Read Groups definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_groups.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Groups list"
    set_fact:
      populate_controller_groups: "{{ (populate_controller_groups | default([])) + item.ansible_facts.controller_groups }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_groups is defined

  - name: "Set Groups Data Structure"
    set_fact:
      controller_groups: "{{ populate_controller_groups }}"
    when: populate_controller_groups is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Groups | Launch groups creation
  import_role:
    name: redhat_cop.controller_configuration.groups
...
