---
- block:
  - name: "Read Hosts definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_hosts.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Hosts list"
    set_fact:
      populate_controller_hosts: "{{ (populate_controller_hosts | default([])) + item.ansible_facts.controller_hosts }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_hosts is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_hosts: "{{ populate_controller_hosts }}"
    when: populate_controller_hosts is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- name: Configure Controller Hosts | Launch Hosts creation
  import_role:
    name: redhat_cop.controller_configuration.hosts
...
