---
- name: Include Inventories list
  include_vars:
    file: "{{ __inventories_variables_file_item }}"
  loop:
    - "{{ dir_orgs_vars }}/{{ orgs }}/env/common/configure_controller_inventories.yml"
  loop_control:
    loop_var: __inventories_variables_file_item
  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Inventories | Launch inventory creation
  import_role:
    name: redhat_cop.controller_configuration.inventories
...
