---
- block:
  - name: "Read Inventory Source definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_inventory_sources.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Inventory Source list"
    set_fact:
      populate_controller_inventory_sources: "{{ (populate_controller_inventory_sources | default([])) + item.ansible_facts.controller_inventory_sources }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Inventory Source Data Structure"
    set_fact:
      controller_inventory_sources: "{{ populate_controller_inventory_sources }}"
    when: populate_controller_inventory_sources is defined

  when: dir_orgs_vars is defined and orgs is defined and env is defined

- name: Configure Controller Inventory Sources | Launch inventory creation
  import_role:
    name: redhat_cop.controller_configuration.inventory_sources
...
