---
- block:
  - name: "Read Job Launch definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_launch_jobs.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Job Launch list"
    set_fact:
      populate_controller_launch_jobs: "{{ (populate_controller_launch_jobs | default([])) + item.ansible_facts.controller_launch_jobs }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Job Launch Data Structure"
    set_fact:
      controller_launch_jobs: "{{ populate_controller_launch_jobs }}"
    when: populate_controller_launch_jobs is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Job Launch | Launch launch_jobs creation
  import_role:
    name: redhat_cop.controller_configuration.job_launch
...
