---
- block:
  - name: "Read Labels definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_labels.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Labels list"
    set_fact:
      populate_controller_labels: "{{ (populate_controller_labels | default([])) + item.ansible_facts.controller_labels }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_labels is defined

  - name: "Set Labels Data Structure"
    set_fact:
      controller_labels: "{{ populate_controller_labels }}"
    when: populate_controller_labels is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Labels | Launch labels creation
  import_role:
    name: redhat_cop.controller_configuration.labels
...
