---
- block:
  - name: "Read Projects definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_projects.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Projects list"
    set_fact:
      populate_controller_project_update: "{{ (populate_controller_project_update | default([])) + item.ansible_facts.controller_projects }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Projects Data Structure"
    set_fact:
      controller_projects: "{{ populate_controller_project_update }}"
    when: populate_controller_projects is defined

  when: orgs is defined and dir_orgs_vars is defined

- name: Update Controller Projects | Launch Project Update
  import_role:
    name: redhat_cop.controller_configuration.project_update
...
