---
- name: Include Roles list
  include_vars:
    file: "{{ __role_variables_file_item }}"
  loop:
    - "{{ dir_orgs_vars }}/{{ orgs }}/env/common/configure_controller_roles.yml"
  loop_control:
    loop_var: __role_variables_file_item
  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Roles | Launch role creation
  import_role:
    name: redhat_cop.controller_configuration.roles
...
