---
- block:
  - name: "Read Roles definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_roles.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Roles list"
    set_fact:
      populate_controller_roles: "{{ (populate_controller_roles | default([])) + item.ansible_facts.controller_roles }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts is defined

  - name: "Set Roles Data Structure"
    set_fact:
      controller_roles: "{{ populate_controller_roles }}"
    when: populate_controller_roles is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Roles | Launch roles creation
  import_role:
    name: redhat_cop.controller_configuration.roles
...
