---
- block:
  - name: "Read Schedules definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_schedules.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Schedules list"
    set_fact:
      populate_controller_schedules: "{{ (populate_controller_schedules | default([])) + item.ansible_facts.controller_schedules }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_schedules is defined

  - name: "Set Schedules Data Structure"
    set_fact:
      controller_schedules: "{{ populate_controller_schedules }}"
    when: populate_controller_schedules is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Schedules | Launch schedules creation
  import_role:
    name: redhat_cop.controller_configuration.schedules
...
