---
- block:
  - name: "Read Settings definitions"
    include_vars:
      file: "{{ item.src }}"
    with_filetree: "{{ dir_orgs_vars }}/env/{{ env }}/controller_settings.d/"
    when: item.state == 'file'
    register: contents

  - name: "Populate Settings list"
    set_fact:
      populate_controller_settings: "{{ (populate_controller_settings | default([])) + item.ansible_facts.controller_settings }}"
    loop: "{{ contents.results }}"
    when: contents.results is defined and item.ansible_facts.controller_settings is defined

  - name: "Set Settings Data Structure"
    set_fact:
      controller_settings: "{{ populate_controller_settings }}"
    when: populate_controller_settings is defined

  when: dir_orgs_vars is defined and orgs is defined

- name: Configure Controller Settings | Launch settings creation
  import_role:
    name: redhat_cop.controller_configuration.settings
...
