---
- name: "Get the current Workflow Job Template Nodes from the API"
  set_fact:
    # wfjtn_lookvar: "{{ (wfjtn_lookvar|default({})) | combine({wfjtn_lookvar_item.summary_fields.workflow_job_template.name: {'nodes': (wfjtn_lookvar[wfjtn_lookvar_item.summary_fields.workflow_job_template.name]['nodes']|default([]) + [wfjtn_lookvar_item] | flatten), 'wfjtn_url': wfjtn_lookvar_item.related.workflow_job_template}}) }}"
    wfjtn_lookvar: "{{ (wfjtn_lookvar|default({})) | combine({wfjtn_lookvar_item.summary_fields.workflow_job_template.name: {'nodes': (wfjtn_lookvar[wfjtn_lookvar_item.summary_fields.workflow_job_template.name]['nodes']|default([]) + [wfjtn_lookvar_item] | flatten), 'organization': workflow_job_template_organization}}) }}"
    needed_paths: "{{ ((needed_paths | default([])) + [workflow_job_template_organization]) | flatten | unique }}"
  vars:
    workflow_job_template_organization: "{{ query('ansible.controller.controller_api', wfjtn_lookvar_item.related.workflow_job_template, host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs)[0].summary_fields.organization.name | default('ORGANIZATIONLESS') }}"
  loop: "{{ query('ansible.controller.controller_api', 'api/v2/workflow_job_template_nodes/', host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs, return_all=true) }}"
  loop_control:
    loop_var: wfjtn_lookvar_item
    label: "{{ workflow_job_template_organization + ' - ' + wfjtn_lookvar_item.summary_fields.workflow_job_template.name }}"

- name: "Create the output directory for workflow job template nodes: {{ output_path }}/<ORGANIZATION_NAME>"
  file:
    path: "{{ output_path }}/{{ needed_path }}"
    state: directory
    mode: '0755'
  loop: "{{ needed_paths | default([]) }}"
  loop_control:
    loop_var: needed_path
    label: "{{ output_path }}/{{ needed_path }}"

- name: "Add current workflow job template nodes to the output yaml file: {{ output_path }}/<ORGANIZATION_NAME>/current_workflow_job_template_nodes_{{ workflow_job_template_name }}.yaml"
  template:
    src: "templates/current_workflow_job_template_nodes.j2"
    dest: "{{ output_path }}/{{ current_wfjtn_asset_value.value.organization }}/current_workflow_job_template_nodes_{{ workflow_job_template_name }}.yaml"
    mode: '0644'
  vars:
    workflow_job_template_name: "{{ current_wfjtn_asset_value.key }}"
    # workflow_job_template_organization: "{{ query('ansible.controller.controller_api', current_wfjtn_asset_value.value.wfjtn_url, host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs)[0].summary_fields.organization.name | default('ToDo: The WF node  must have an organization') }}"
  loop: "{{ wfjtn_lookvar | default({}) | dict2items }}"
  loop_control:
    loop_var: current_wfjtn_asset_value
    label: "{{ output_path }}/{{ current_wfjtn_asset_value.value.organization }}/current_workflow_job_template_nodes_{{ workflow_job_template_name }}.yaml"
...
